// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0XaWXCdNj90t0n2Z2no-5mTpzbof3ib8',
    appId: '1:1025006753255:web:1420bfb145a0a9169a9942',
    messagingSenderId: '1025006753255',
    projectId: 'crudusers-4dba6',
    authDomain: 'crudusers-4dba6.firebaseapp.com',
    storageBucket: 'crudusers-4dba6.firebasestorage.app',
    measurementId: 'G-553D5NN7X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjBr5NZs1DC8vyUnkagT3ziB5ZlRGoXS4',
    appId: '1:1025006753255:android:6de6828d2d6ea53d9a9942',
    messagingSenderId: '1025006753255',
    projectId: 'crudusers-4dba6',
    storageBucket: 'crudusers-4dba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmtw4fHRe1BftjyDwA5P1h-vpctLiR8VI',
    appId: '1:1025006753255:ios:51e422f128b5ecbd9a9942',
    messagingSenderId: '1025006753255',
    projectId: 'crudusers-4dba6',
    storageBucket: 'crudusers-4dba6.firebasestorage.app',
    iosBundleId: 'com.example.crudusers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmtw4fHRe1BftjyDwA5P1h-vpctLiR8VI',
    appId: '1:1025006753255:ios:51e422f128b5ecbd9a9942',
    messagingSenderId: '1025006753255',
    projectId: 'crudusers-4dba6',
    storageBucket: 'crudusers-4dba6.firebasestorage.app',
    iosBundleId: 'com.example.crudusers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0XaWXCdNj90t0n2Z2no-5mTpzbof3ib8',
    appId: '1:1025006753255:web:9302cf4539bd70529a9942',
    messagingSenderId: '1025006753255',
    projectId: 'crudusers-4dba6',
    authDomain: 'crudusers-4dba6.firebaseapp.com',
    storageBucket: 'crudusers-4dba6.firebasestorage.app',
    measurementId: 'G-TXQV8HSV7Q',
  );
}
